language: cpp
env:
  global:
    - secure: "Pu2hPyp3Ym3hmkW9iXVZObfE7tA3ITSaeR05VguJ9czJAMgaT7LmEN4LDoR2sQHbRAv+8QngbNUFpglzvZLIBIEefyEA39DThZptkKJ+hCUerRajfmXywSXCwPC7A1uTEY1YoUDlGvxVZA3Z7f17GFtKtDuHjLSWmrxHAM6wjK+qCweEq0umJJ+N+2DX2UpVLlWgYoknYSGipfjHRBEgPp4NRh08yvpDTFYSVQeL0qL7LbyAtkx6qhLCK6JZ2CsP3INQOoRwc8jP6VIFbuoHl3lkOzayNM49/e9wDdZ8FGqp0HjUFi7EYi/78Uvje7CrgdCiSVwoHbtAvcyPYcxu+qXzwh4AxslRL7UJtOzTbRaXfJvqt2oqtttFjD0Dk/iwnAthg7Su6UohivcUVj/9p1X1KdDbLJcoTag/MBcZP7VJDgnHjyqYwVciT1ZV0RWfuLBI584vFMTlsdzFXt384mUTCN02BOnRnw3Miq4a5irFXnDy23TdGersk7b//FPIBIhPv/wxCjUkJzTmt7ska5jACb/FHUoOyrE5mQLSVZbh/zlsIKf8yWZy7q7caowmwyPYZtAqNZWj1JmVs2c+0RmX2c76kCTHX4ocCcDx1QqV49/+R1Ah+pA7X7kcr9MklzL9z/lkAA7z5SF/UzdoGfBNicMKz5hUFixBqZ04ATw="
branches:
    only:
        - /^v\d+\..+$/
        - master
        - ci
        - travis
        - hunter
        - coverity
        - /^travis-.*$/
        - /^release.*$/
matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
          env:
              - CUDA=ON
              - CUDA_VERSION=10
        - os: linux
          dist: trusty
          sudo: required
          env:
              - CUDA=ON
              - CUDA_VERSION=9
        - os: linux
          dist: trusty
          sudo: required
          env:
              - CUDA=ON
              - CUDA_VERSION=8
        - os: osx
          osx_image: xcode9.2
          env:
              - CUDA=ON
              - CUDA_VERSION=9
cache:
    directories:
        - $HOME/.local
before_install:
  - |
    if [ "$TRAVIS_OS_NAME" = linux ]; then
      echo "Checking format of sourcecode..."
      find . -type f \( -name '*.cpp' -o -name '*.h' -o -name '*.cu' -o -name '*.cuh' \) -print0 | xargs -r0 clang-format -i
      git diff --color # --exit-code
    fi
  - |
    if [ "$TRAVIS_OS_NAME" = linux ]; then
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      sudo apt-get -q update
      sudo apt-get -qy install g++-6
      scripts/install_cmake.sh
      . scripts/install-cuda-ubuntu1604.sh $CUDA_VERSION
      pyenv global 3.6
      pip install --user requests gitpython
      if [ "$CUDA_VERSION" = "8" ]; then
        sudo apt-get -qy install g++-5
      fi
      export CC=gcc-6
      export CXX=g++-6
    elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
      curl -L https://developer.nvidia.com/compute/cuda/9.1/Prod/local_installers/cuda_9.1.128_mac -o $HOME/cuda_9.1.128_mac.dmg
      hdiutil mount $HOME/cuda_9.1.128_mac.dmg
      sleep 5
      ls -ltr /Volumes/CUDAMacOSXInstaller/CUDAMacOSXInstaller.app/Contents/MacOS
      sudo /Volumes/CUDAMacOSXInstaller/CUDAMacOSXInstaller.app/Contents/MacOS/CUDAMacOSXInstaller --accept-eula --no-window; export BREW_STATUS=$?
      echo "Brew status $BREW_STATUS"
      if [ $BREW_STATUS -ne 0 ]; then
        echo "Brew Failed"
        exit $BREW_STATUS
      fi
      HOMEBREW_NO_AUTO_UPDATE=1 brew install -q python3
      pip3 install -q requests gitpython
    fi
script: |
    if [ "$CUDA_VERSION" = "8" ]; then
      cmake -DCUDA_HOST_COMPILER=/usr/bin/gcc-5 -DHUNTER_JOBS_NUMBER=4 -DETHASHCUDA=$CUDA -DETHASHCL=ON -DAPICORE=ON -H. -Bbuild
    else
      cmake -DHUNTER_JOBS_NUMBER=4 -DETHASHCUDA=$CUDA -DETHASHCL=ON -DAPICORE=ON -H. -Bbuild
    fi
    cmake --build build --target package -- -j4
    #build/kawpowminer/kawpowminer --help
    if [ "$TRAVIS_OS_NAME" = linux ]; then ldd -v build/kawpowminer/kawpowminer; fi
    if [ "$TRAVIS_OS_NAME" = osx ]; then otool -L build/kawpowminer/kawpowminer; fi
    . build/kawpowminer/buildinfo.sh
    mkdir package
    mv build/kawpowminer.tar.gz package/$PROJECT_NAME-$PROJECT_VERSION-cuda-$CUDA_VERSION-$SYSTEM_NAME-$SYSTEM_PROCESSOR.tar.gz


deploy:
  - provider: releases
    api_key:
      secure: "tDcvfJiWtLDTalXBI7vGTFKt6epnoGmkQgcaaKW6OkYso55pIv003xlOUZ+PzzlOzYEDAmtgDIh63Th+ev2r7zrMBCzw6ntSb3c+bqhjTRo+G+2QWN89QH8bN6d2To8Roa0vlDHS4ADEqoxb3+7v7qn5LRoaZu25nsqqfFVHM5VPez5MMFKkJvqcvEOXRVsQM1apYjsTXc+mxJF0Iel+YhTbqjt+8j4epAvtgSzptTpzSwnqx5GCwb9SuHFrhI9XieC3RC75br9/KW/gLjfkRaOKsbdds1wDGvQwDqkimZOdcN7BoaH6DJqQYQWQg5kxlRxdaXRiIzRCElOKncL6FyyfhCdUQbNd07ujjfKPtTCvWXeLDjeIoQ5h7Lo7QEOlBl4yxi+1hKR5Pn/nxv81kfd+bWoc+uPA/UPbX2EqqDss5deqYKpugToulphCCxUiNFpaEgmDXads3H1UgMaBF5qepkAUckbquFLs2kC8MiD6uZsjzlVpvjNJbiib6ofRt+Z1IuIjT+w63afNu43tMHQWii1tFpU6NubxiDYYuW0E4Rd4Nil8fvy/vGh5jGLVitpUk/xk5Pguf+GtMuZgasbZxUD3OI5MvKQ/LPwbIrJRJWtqD02TZmnDZ6O5k98qWhn8VmWbteu0BMeVofot8Bziq7Cmx675izLunZ0fkpg="
    file_glob: true
    file: package/*
    skip_cleanup: true
    on:
      tags: true
